export const stockInData1 = [
    {
        id: 1,
        code: "PN000001",
        imported_date: "2025-03-10T10:16:43.000Z",
        invoice: {
            id: 1,
            bl_no: "ONEYTS4NU3550700",
            invoice_date: "2024-11-24T00:00:00.000Z",
            total_piece: 1065,
            total_pallet: 3,
            note: null,
            packing_slips: [
                {
                    id: 2,
                    container_no: "TEMU0521450",
                    seal_no: "CN425821A",
                    invoice_id: 1,
                    note: null,
                    packing_details: [
                        {
                            id: 16,
                            vendor_code: null,
                            piece: 92,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "92",
                            note: null,
                            product: {
                                id: 10,
                                name: null,
                                internal_code: "53006",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 18,
                            vendor_code: null,
                            piece: 112,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "112",
                            note: null,
                            product: {
                                id: 8,
                                name: null,
                                internal_code: "31550",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 17,
                            vendor_code: null,
                            piece: 288,
                            pallet: 2,
                            piece_used: 288,
                            pallet_used: 2,
                            remark: "144*2",
                            note: null,
                            product: {
                                id: 11,
                                name: null,
                                internal_code: "42323",
                                raw_weight: 12.5,
                                finished_weight: 10.6,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                    ],
                },
                {
                    id: 1,
                    container_no: "TEMU0629370",
                    seal_no: "CN42586AS",
                    invoice_id: 1,
                    note: null,
                    packing_details: [
                        {
                            id: 1,
                            vendor_code: null,
                            piece: 92,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "92",
                            note: null,
                            product: {
                                id: 10,
                                name: null,
                                internal_code: "53006",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 2,
                            vendor_code: null,
                            piece: 288,
                            pallet: 2,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "144*2",
                            note: null,
                            product: {
                                id: 11,
                                name: null,
                                internal_code: "42323",
                                raw_weight: 12.5,
                                finished_weight: 10.6,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 3,
                            vendor_code: null,
                            piece: 112,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "112",
                            note: null,
                            product: {
                                id: 7,
                                name: null,
                                internal_code: "55055",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 4,
                            vendor_code: null,
                            piece: 176,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "176",
                            note: null,
                            product: {
                                id: 8,
                                name: null,
                                internal_code: "31550",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 5,
                            vendor_code: null,
                            piece: 280,
                            pallet: 2,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "140*2",
                            note: null,
                            product: {
                                id: 8,
                                name: null,
                                internal_code: "31550",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 6,
                            vendor_code: null,
                            piece: 232,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "232",
                            note: null,
                            product: {
                                id: 4,
                                name: null,
                                internal_code: "55054",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 7,
                            vendor_code: null,
                            piece: 304,
                            pallet: 2,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "100+204",
                            note: null,
                            product: {
                                id: 11,
                                name: null,
                                internal_code: "42323",
                                raw_weight: 12.5,
                                finished_weight: 10.6,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 8,
                            vendor_code: null,
                            piece: 152,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "152",
                            note: null,
                            product: {
                                id: 7,
                                name: null,
                                internal_code: "55055",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 9,
                            vendor_code: null,
                            piece: 140,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "140",
                            note: null,
                            product: {
                                id: 6,
                                name: null,
                                internal_code: "31375",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 10,
                            vendor_code: null,
                            piece: 282,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "282",
                            note: null,
                            product: {
                                id: 8,
                                name: null,
                                internal_code: "31550",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 11,
                            vendor_code: null,
                            piece: 144,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "144",
                            note: null,
                            product: {
                                id: 11,
                                name: null,
                                internal_code: "42323",
                                raw_weight: 12.5,
                                finished_weight: 10.6,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                        {
                            id: 12,
                            vendor_code: null,
                            piece: 236,
                            pallet: 1,
                            piece_used: 0,
                            pallet_used: 0,
                            remark: "236",
                            note: null,
                            product: {
                                id: 7,
                                name: null,
                                internal_code: "55055",
                                raw_weight: 0,
                                finished_weight: 0,
                                workpiece_weight: 0,
                                unit: null,
                                note: null,
                            },
                        },
                    ],
                },
            ],
        },
        packing_slip: {
            id: 2,
            container_no: "TEMU0521450",
            seal_no: "CN425821A",
            invoice_id: 1,
            note: null,
        },
        packing_detail: {
            id: 17,
            vendor_code: null,
            piece: 288,
            pallet: 2,
            piece_used: 288,
            pallet_used: 2,
            remark: "144*2",
            note: null,
            product: {
                id: 11,
                name: null,
                internal_code: "42323",
                raw_weight: 12.5,
                finished_weight: 10.6,
                workpiece_weight: 0,
                unit: null,
                note: null,
            },
        },
        receipt_details: [
            {
                id: 2,
                code: "N000002",
                po: "",
                price: 0,
                details: "",
                wrong_code: "",
                location: "",
                quantity: 144,
                pallet: 1,
                quantity_used: 0,
                pallet_used: 0,
                duc_date: null,
                gc_date: null,
                warehouse: {
                    id: 8,
                    name: "Kho An Dương",
                    code: "K000001",
                    note: null,
                },
                supplier: {
                    id: 8,
                    name: "唐山 T",
                },
                stamp: {
                    id: 1,
                    cus_code: "1112K",
                    note: null,
                    total_stamp: 0,
                    product: {
                        id: 11,
                        name: null,
                        internal_code: "42323",
                        raw_weight: 12.5,
                        finished_weight: 10.6,
                        workpiece_weight: 0,
                        unit: null,
                        note: null,
                    },
                    customer: {
                        id: 1,
                        name: "AP",
                        code: null,
                        note: null,
                    },
                },
            },
            {
                id: 1,
                code: "N000001",
                po: "",
                price: 0,
                details: "",
                wrong_code: "",
                location: "",
                quantity: 144,
                pallet: 1,
                quantity_used: 144,
                pallet_used: 1,
                duc_date: null,
                gc_date: "2025-03-10T03:21:14.701Z",
                warehouse: {
                    id: 8,
                    name: "Kho An Dương",
                    code: "K000001",
                    note: null,
                },
                supplier: {
                    id: 3,
                    name: "MINH ANH",
                },
                stamp: {
                    id: 1,
                    cus_code: "1112K",
                    note: null,
                    total_stamp: 0,
                    product: {
                        id: 11,
                        name: null,
                        internal_code: "42323",
                        raw_weight: 12.5,
                        finished_weight: 10.6,
                        workpiece_weight: 0,
                        unit: null,
                        note: null,
                    },
                    customer: {
                        id: 1,
                        name: "AP",
                        code: null,
                        note: null,
                    },
                },
            },
        ],
        quantity: 288,
        pallet: 2,
        quantity_used: 144,
        pallet_used: 1,
    },
];
